language: go
sudo: false

matrix:
  include:
    - go: 1.12.x
    - go: 1.x
      env: LATEST=true
    - go: tip
    - go: master
  allow_failures:
    - go: tip
    - go: master

script:
  - go test ./... -v